# Configurações do Banco de Dados
# PostgreSQL
URL_POSTGRES=jdbc:postgresql://localhost:5432/hermescomercialdb
USER_POSTGRES=postgres
PASSWORD_POSTGRES=Abacaxi@121

# MySQL
URL_MYSQL=jdbc:mysql://localhost:3306/hermescomercialdb
USER_MYSQL=root
PASSWORD_MYSQL=Abacaxi@123

# SQLite
PATH_SQLITE_DB=jdbc:sqlite:hermes_pdv.db

# Configurações da Aplicação
APP_NAME=Hermes Comercial PDV
APP_VERSION=1.0.0
APP_DEBUG=true

# Configurações de Log
LOG_LEVEL=INFO
LOG_FILE_PATH=logs/hermes_pdv.log

# Configurações de Interface
THEME=default
LANGUAGE=pt_BR
COUNTRY=BR

# Configurações de PDV
PDV_CAIXA_NUMERO=1
PDV_IMPRIMIR_CUPOM=true
PDV_IMPRIMIR_ETIQUETA=false
